// Code generated by github.com/whyrusleeping/cbor-gen. DO NOT EDIT.

package datamodel

import (
	"fmt"
	"io"
	"math"
	"sort"

	cid "github.com/ipfs/go-cid"
	cbg "github.com/whyrusleeping/cbor-gen"
	xerrors "golang.org/x/xerrors"
)

var _ = xerrors.Errorf
var _ = cid.Undef
var _ = math.E
var _ = sort.Sort

func (t *ListArgumentsModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{160}); err != nil {
		return err
	}
	return nil
}

func (t *ListArgumentsModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ListArgumentsModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("ListArgumentsModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 0)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *ProviderModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{163}); err != nil {
		return err
	}

	// t.Weight (uint64) (uint64)
	if len("weight") > 8192 {
		return xerrors.Errorf("Value in field \"weight\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("weight"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("weight")); err != nil {
		return err
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajUnsignedInt, uint64(t.Weight)); err != nil {
		return err
	}

	// t.Endpoint (string) (string)
	if len("endpoint") > 8192 {
		return xerrors.Errorf("Value in field \"endpoint\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("endpoint"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("endpoint")); err != nil {
		return err
	}

	if len(t.Endpoint) > 8192 {
		return xerrors.Errorf("Value in field t.Endpoint was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Endpoint))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Endpoint)); err != nil {
		return err
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return xerrors.Errorf("Value in field \"provider\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("provider"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("provider")); err != nil {
		return err
	}

	if err := t.Provider.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *ProviderModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ProviderModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("ProviderModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 8)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Weight (uint64) (uint64)
		case "weight":

			{

				maj, extra, err = cr.ReadHeader()
				if err != nil {
					return err
				}
				if maj != cbg.MajUnsignedInt {
					return fmt.Errorf("wrong type for uint64 field")
				}
				t.Weight = uint64(extra)

			}
			// t.Endpoint (string) (string)
		case "endpoint":

			{
				sval, err := cbg.ReadStringWithMax(cr, 8192)
				if err != nil {
					return err
				}

				t.Endpoint = string(sval)
			}
			// t.Provider (did.DID) (struct)
		case "provider":

			{

				if err := t.Provider.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Provider: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *ListOKModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{161}); err != nil {
		return err
	}

	// t.Providers ([]datamodel.ProviderModel) (slice)
	if len("providers") > 8192 {
		return xerrors.Errorf("Value in field \"providers\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("providers"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("providers")); err != nil {
		return err
	}

	if len(t.Providers) > 8192 {
		return xerrors.Errorf("Slice value in field t.Providers was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajArray, uint64(len(t.Providers))); err != nil {
		return err
	}
	for _, v := range t.Providers {
		if err := v.MarshalCBOR(cw); err != nil {
			return err
		}

	}
	return nil
}

func (t *ListOKModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = ListOKModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("ListOKModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 9)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Providers ([]datamodel.ProviderModel) (slice)
		case "providers":

			maj, extra, err = cr.ReadHeader()
			if err != nil {
				return err
			}

			if extra > 8192 {
				return fmt.Errorf("t.Providers: array too large (%d)", extra)
			}

			if maj != cbg.MajArray {
				return fmt.Errorf("expected cbor array")
			}

			if extra > 0 {
				t.Providers = make([]ProviderModel, extra)
			}

			for i := 0; i < int(extra); i++ {
				{
					var maj byte
					var extra uint64
					var err error
					_ = maj
					_ = extra
					_ = err

					{

						if err := t.Providers[i].UnmarshalCBOR(cr); err != nil {
							return xerrors.Errorf("unmarshaling t.Providers[i]: %w", err)
						}

					}

				}
			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *RegisterArgumentsModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{162}); err != nil {
		return err
	}

	// t.Endpoint (string) (string)
	if len("endpoint") > 8192 {
		return xerrors.Errorf("Value in field \"endpoint\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("endpoint"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("endpoint")); err != nil {
		return err
	}

	if len(t.Endpoint) > 8192 {
		return xerrors.Errorf("Value in field t.Endpoint was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len(t.Endpoint))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string(t.Endpoint)); err != nil {
		return err
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return xerrors.Errorf("Value in field \"provider\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("provider"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("provider")); err != nil {
		return err
	}

	if err := t.Provider.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *RegisterArgumentsModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = RegisterArgumentsModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("RegisterArgumentsModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 8)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Endpoint (string) (string)
		case "endpoint":

			{
				sval, err := cbg.ReadStringWithMax(cr, 8192)
				if err != nil {
					return err
				}

				t.Endpoint = string(sval)
			}
			// t.Provider (did.DID) (struct)
		case "provider":

			{

				if err := t.Provider.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Provider: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
func (t *DeregisterArgumentsModel) MarshalCBOR(w io.Writer) error {
	if t == nil {
		_, err := w.Write(cbg.CborNull)
		return err
	}

	cw := cbg.NewCborWriter(w)

	if _, err := cw.Write([]byte{161}); err != nil {
		return err
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return xerrors.Errorf("Value in field \"provider\" was too long")
	}

	if err := cw.WriteMajorTypeHeader(cbg.MajTextString, uint64(len("provider"))); err != nil {
		return err
	}
	if _, err := cw.WriteString(string("provider")); err != nil {
		return err
	}

	if err := t.Provider.MarshalCBOR(cw); err != nil {
		return err
	}
	return nil
}

func (t *DeregisterArgumentsModel) UnmarshalCBOR(r io.Reader) (err error) {
	*t = DeregisterArgumentsModel{}

	cr := cbg.NewCborReader(r)

	maj, extra, err := cr.ReadHeader()
	if err != nil {
		return err
	}
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()

	if maj != cbg.MajMap {
		return fmt.Errorf("cbor input should be of type map")
	}

	if extra > cbg.MaxLength {
		return fmt.Errorf("DeregisterArgumentsModel: map struct too large (%d)", extra)
	}

	n := extra

	nameBuf := make([]byte, 8)
	for i := uint64(0); i < n; i++ {
		nameLen, ok, err := cbg.ReadFullStringIntoBuf(cr, nameBuf, 8192)
		if err != nil {
			return err
		}

		if !ok {
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(cr, func(cid.Cid) {}); err != nil {
				return err
			}
			continue
		}

		switch string(nameBuf[:nameLen]) {
		// t.Provider (did.DID) (struct)
		case "provider":

			{

				if err := t.Provider.UnmarshalCBOR(cr); err != nil {
					return xerrors.Errorf("unmarshaling t.Provider: %w", err)
				}

			}

		default:
			// Field doesn't exist on this type, so ignore it
			if err := cbg.ScanForLinks(r, func(cid.Cid) {}); err != nil {
				return err
			}
		}
	}

	return nil
}
