// Code generated by github.com/alanshaw/dag-json-gen. DO NOT EDIT.

package datamodel

import (
	"errors"
	"fmt"
	"io"
	"math"
	"sort"

	jsg "github.com/alanshaw/dag-json-gen"
	cid "github.com/ipfs/go-cid"
)

var _ = cid.Undef
var _ = math.E
var _ = sort.Sort
var _ = errors.Is

func (t *ListArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ListArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ListArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("ListArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("ListArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("ListArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("ListArgumentsModel: string too large")
				}
				return fmt.Errorf("ListArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("ListArgumentsModel: %w", err)
			}
			switch name {
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ListArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("ListArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("ListArgumentsModel: map too large")
			}
		}
	}

	return nil
}
func (t *ProviderModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Endpoint (string) (string)
	if len("endpoint") > 8192 {
		return fmt.Errorf("String in field \"endpoint\" was too long")
	}
	if err := jw.WriteString(string("endpoint")); err != nil {
		return fmt.Errorf("\"endpoint\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Endpoint) > 8192 {
		return fmt.Errorf("String in field t.Endpoint was too long")
	}
	if err := jw.WriteString(string(t.Endpoint)); err != nil {
		return fmt.Errorf("t.Endpoint: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return fmt.Errorf("String in field \"provider\" was too long")
	}
	if err := jw.WriteString(string("provider")); err != nil {
		return fmt.Errorf("\"provider\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Provider.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Provider: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Weight (uint64) (uint64)
	if len("weight") > 8192 {
		return fmt.Errorf("String in field \"weight\" was too long")
	}
	if err := jw.WriteString(string("weight")); err != nil {
		return fmt.Errorf("\"weight\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}

	if err := jw.WriteUint64(uint64(t.Weight)); err != nil {
		return fmt.Errorf("t.Weight: %w", err)
	}

	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ProviderModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ProviderModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("ProviderModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("ProviderModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("ProviderModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("ProviderModel: string too large")
				}
				return fmt.Errorf("ProviderModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("ProviderModel: %w", err)
			}
			switch name {

			// t.Endpoint (string) (string)
			case "endpoint":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Endpoint: string too long")
						}
						return fmt.Errorf("t.Endpoint: %w", err)
					}
					t.Endpoint = string(sval)
				}

				// t.Provider (did.DID) (struct)
			case "provider":

				if err := t.Provider.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Provider: %w", err)
				}

				// t.Weight (uint64) (uint64)
			case "weight":
				{

					nval, err := jr.ReadNumberAsUint64()
					if err != nil {
						return fmt.Errorf("t.Weight: %w", err)
					}
					t.Weight = uint64(nval)

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ProviderModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("ProviderModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("ProviderModel: map too large")
			}
		}
	}

	return nil
}
func (t *ListOKModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Providers ([]datamodel.ProviderModel) (slice)
	if len("providers") > 8192 {
		return fmt.Errorf("String in field \"providers\" was too long")
	}
	if err := jw.WriteString(string("providers")); err != nil {
		return fmt.Errorf("\"providers\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Providers) > 8192 {
		return fmt.Errorf("Slice value in field t.Providers was too long")
	}

	if err := jw.WriteArrayOpen(); err != nil {
		return fmt.Errorf("t.Providers: %w", err)
	}
	for i, v := range t.Providers {
		if i > 0 {
			if err := jw.WriteComma(); err != nil {
				return fmt.Errorf("t.Providers: %w", err)
			}
		}
		if err := v.MarshalDagJSON(jw); err != nil {
			return fmt.Errorf("v: %w", err)
		}
	}
	if err := jw.WriteArrayClose(); err != nil {
		return fmt.Errorf("t.Providers: %w", err)
	}

	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *ListOKModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = ListOKModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("ListOKModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("ListOKModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("ListOKModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("ListOKModel: string too large")
				}
				return fmt.Errorf("ListOKModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("ListOKModel: %w", err)
			}
			switch name {

			// t.Providers ([]datamodel.ProviderModel) (slice)
			case "providers":
				{

					if err := jr.ReadArrayOpen(); err != nil {
						return fmt.Errorf("t.Providers: %w", err)
					}

					close, err := jr.PeekArrayClose()
					if err != nil {
						return fmt.Errorf("t.Providers: %w", err)
					}
					if close {
						if err := jr.ReadArrayClose(); err != nil {
							return fmt.Errorf("t.Providers: %w", err)
						}

					} else {
						for i := 0; i < 8192; i++ {
							item := make([]ProviderModel, 1)

							if err := item[0].UnmarshalDagJSON(jr); err != nil {
								return fmt.Errorf("unmarshaling item[0]: %w", err)
							}

							t.Providers = append(t.Providers, item[0])

							close, err := jr.ReadArrayCloseOrComma()
							if err != nil {
								return fmt.Errorf("t.Providers: %w", err)
							}
							if close {
								break
							}
							if i == 8192-1 {
								return fmt.Errorf("t.Providers: slice too large")
							}
						}
					}

				}
			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("ListOKModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("ListOKModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("ListOKModel: map too large")
			}
		}
	}

	return nil
}
func (t *RegisterArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}
	written := 0

	// t.Endpoint (string) (string)
	if len("endpoint") > 8192 {
		return fmt.Errorf("String in field \"endpoint\" was too long")
	}
	if err := jw.WriteString(string("endpoint")); err != nil {
		return fmt.Errorf("\"endpoint\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if len(t.Endpoint) > 8192 {
		return fmt.Errorf("String in field t.Endpoint was too long")
	}
	if err := jw.WriteString(string(t.Endpoint)); err != nil {
		return fmt.Errorf("t.Endpoint: %w", err)
	}
	written++
	if written > 0 {
		if err := jw.WriteComma(); err != nil {
			return err
		}
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return fmt.Errorf("String in field \"provider\" was too long")
	}
	if err := jw.WriteString(string("provider")); err != nil {
		return fmt.Errorf("\"provider\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Provider.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Provider: %w", err)
	}
	written++
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *RegisterArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = RegisterArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("RegisterArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("RegisterArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("RegisterArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("RegisterArgumentsModel: string too large")
				}
				return fmt.Errorf("RegisterArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("RegisterArgumentsModel: %w", err)
			}
			switch name {

			// t.Endpoint (string) (string)
			case "endpoint":
				{
					sval, err := jr.ReadString(8192)
					if err != nil {
						if errors.Is(err, jsg.ErrLimitExceeded) {
							return fmt.Errorf("t.Endpoint: string too long")
						}
						return fmt.Errorf("t.Endpoint: %w", err)
					}
					t.Endpoint = string(sval)
				}

				// t.Provider (did.DID) (struct)
			case "provider":

				if err := t.Provider.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Provider: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("RegisterArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("RegisterArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("RegisterArgumentsModel: map too large")
			}
		}
	}

	return nil
}
func (t *DeregisterArgumentsModel) MarshalDagJSON(w io.Writer) error {
	jw := jsg.NewDagJsonWriter(w)
	if t == nil {
		err := jw.WriteNull()
		return err
	}
	if err := jw.WriteObjectOpen(); err != nil {
		return err
	}

	// t.Provider (did.DID) (struct)
	if len("provider") > 8192 {
		return fmt.Errorf("String in field \"provider\" was too long")
	}
	if err := jw.WriteString(string("provider")); err != nil {
		return fmt.Errorf("\"provider\": %w", err)
	}
	if err := jw.WriteObjectColon(); err != nil {
		return err
	}
	if err := t.Provider.MarshalDagJSON(jw); err != nil {
		return fmt.Errorf("t.Provider: %w", err)
	}
	if err := jw.WriteObjectClose(); err != nil {
		return err
	}
	return nil
}
func (t *DeregisterArgumentsModel) UnmarshalDagJSON(r io.Reader) (err error) {
	*t = DeregisterArgumentsModel{}

	jr := jsg.NewDagJsonReader(r)
	defer func() {
		if err == io.EOF {
			err = io.ErrUnexpectedEOF
		}
	}()
	if err := jr.ReadObjectOpen(); err != nil {
		return fmt.Errorf("DeregisterArgumentsModel: %w", err)
	}
	close, err := jr.PeekObjectClose()
	if err != nil {
		return fmt.Errorf("DeregisterArgumentsModel: %w", err)
	}
	if close {
		if err := jr.ReadObjectClose(); err != nil {
			return fmt.Errorf("DeregisterArgumentsModel: %w", err)
		}
	} else {
		for i := uint64(0); i < 8192; i++ {
			name, err := jr.ReadString(8192)
			if err != nil {
				if errors.Is(err, jsg.ErrLimitExceeded) {
					return fmt.Errorf("DeregisterArgumentsModel: string too large")
				}
				return fmt.Errorf("DeregisterArgumentsModel: %w", err)
			}
			if err := jr.ReadObjectColon(); err != nil {
				return fmt.Errorf("DeregisterArgumentsModel: %w", err)
			}
			switch name {

			// t.Provider (did.DID) (struct)
			case "provider":

				if err := t.Provider.UnmarshalDagJSON(jr); err != nil {
					return fmt.Errorf("unmarshaling t.Provider: %w", err)
				}

			default:
				// Field doesn't exist on this type, so ignore it
				if err := jr.DiscardType(); err != nil {
					return fmt.Errorf("DeregisterArgumentsModel: ignoring field %s: %w", name, err)
				}
			}

			close, err := jr.ReadObjectCloseOrComma()
			if err != nil {
				return fmt.Errorf("DeregisterArgumentsModel: %w", err)
			}
			if close {
				break
			}
			if i == 8192-1 {
				return fmt.Errorf("DeregisterArgumentsModel: map too large")
			}
		}
	}

	return nil
}
